"""Stable quality issue codes for reviews and export blockers."""

from __future__ import annotations

from enum import Enum


class IssueCode(str, Enum):
    CONTENT_ATOM_MISSING = "CONTENT_ATOM_MISSING"
    DEPTH_EMPTY = "DEPTH_EMPTY"
    DEPTH_GENERIC = "DEPTH_GENERIC"
    FILLER_REEL = "FILLER_REEL"
    DUPLICATE_LEARNING_JOB = "DUPLICATE_LEARNING_JOB"
    UNSUPPORTED_CLAIM = "UNSUPPORTED_CLAIM"
    INSUFFICIENT_SOURCES = "INSUFFICIENT_SOURCES"
    EXPERT_REVIEW_REQUIRED = "EXPERT_REVIEW_REQUIRED"
    LITERAL_TRANSLATION = "LITERAL_TRANSLATION"
    LANGUAGE_REGISTER_MIX = "LANGUAGE_REGISTER_MIX"
    BROKEN_GRAMMAR = "BROKEN_GRAMMAR"
    REPEATED_OPENING = "REPEATED_OPENING"
    REPEATED_CLOSING = "REPEATED_CLOSING"
    BAD_TRANSITION = "BAD_TRANSITION"
    READ_ALOUD_FAILURE = "READ_ALOUD_FAILURE"
    BAD_LINE_BREAK = "BAD_LINE_BREAK"
    WORD_RANGE = "WORD_RANGE"
    PUNCTUATION_LEAK = "PUNCTUATION_LEAK"
    PROTECTED_SPAN_CHANGED = "PROTECTED_SPAN_CHANGED"
    FILMING_CUE_LEAK = "FILMING_CUE_LEAK"
    METADATA_LEAK = "METADATA_LEAK"
    PROJECT_MISALIGNMENT = "PROJECT_MISALIGNMENT"
    MAP_REVISION_REQUIRED = "MAP_REVISION_REQUIRED"
    SNAPSHOT_DRIFT = "SNAPSHOT_DRIFT"
    THEORY_RATIO_VIOLATION = "THEORY_RATIO_VIOLATION"
    CHECKPOINT_MISSING = "CHECKPOINT_MISSING"
    TELEPROMPTER_LAYOUT_FAIL = "TELEPROMPTER_LAYOUT_FAIL"


class LessonQualityStatus(str, Enum):
    PASS = "pass"
    NEEDS_REVIEW = "needs_review"
    NEEDS_SOURCES = "needs_sources"
    NEEDS_MAP_REVISION = "needs_map_revision"
    NEEDS_EXPERT_REVIEW = "needs_expert_review"


EXPORT_BLOCKING_STATUSES = frozenset(
    {
        LessonQualityStatus.NEEDS_REVIEW.value,
        LessonQualityStatus.NEEDS_SOURCES.value,
        LessonQualityStatus.NEEDS_MAP_REVISION.value,
        LessonQualityStatus.NEEDS_EXPERT_REVIEW.value,
        "fail",
        "needs_revision",
    }
)
